version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: miner_monitoring_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: miner_monitoring_backend
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: miner_monitoring_frontend
    ports:
      - "3000:80"

volumes:
  mongodb_data:
