version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    environment:
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    cap_add:
      - SYS_ADMIN
    volumes:
      - screenshots:/app/screenshots
      
  frontend:
    build: ./frontend
    ports:
      - "3000:80"

volumes:
  mongodb_data:
  screenshots:
